# This file was generated by GoReleaser. DO NOT EDIT.
cask "iso" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ba222ad8d72b3314f48cd041fb754e3ff57e89353fd03705cf46c42fc5f1f3b8"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "507a5c7c96ea9b6792b76eb55b12c853c765856977a60f7f7ce7f0d9a898be4e"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "303dcef5244bd34c3ac266d8376a487d0e16906540301e4c07129d078a7e70c5"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "acd5f640e9a54a131ee15784baeeebe761d94b33372916833b591f0c15e7c1bd"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iso"
  desc "CLI for ISO standards lookup via the official ISO Open Data catalogue"
  homepage "https://github.com/Robworks-Code/iso-lookup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iso"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iso"]
    end
  end

  # No zap stanza required

end
