# This file was generated by GoReleaser. DO NOT EDIT.
cask "iso" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "72ea4da430907ec6ea2b0a380f02981ebc1a225fc3f8bb7a896f08de14d1b2ef"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f892530bd2bd983facbadf0b1fc99770f08101f41c9dd78a61099dd1e214488"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9667d8bd3422df3a57fb87fb731d36847a3f57aac53b85696f8e6df3ee7a5ee8"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a89310fb72ac19ec0ded6a1d8e4c86a5b5b8a26e35c4caa33f3ce5c80a56888"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iso"
  desc "CLI for ISO standards lookup via the official ISO Open Data catalogue"
  homepage "https://github.com/Robworks-Code/iso-lookup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iso"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iso"]
    end
  end

  # No zap stanza required

end
