# This file was generated by GoReleaser. DO NOT EDIT.
cask "iso" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e939589346ea2557874ab96450f8a45980a89f1eaef22770a9e90cc034e7ec82"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "448179e0a28f6ac95baa081cbe6e7f712e905c0b8f6b86255c03886f0c7c649e"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f35db9fee18802636de85976ea9f098b75fc62d59d9309f661a180d245f44c7"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "53a8772a1ab862c1d2bf5eede3537b5075aa1e3bbd7c45c7ecf080385207cbea"
      url "https://github.com/Robworks-Code/iso-lookup/releases/download/v#{version}/iso_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iso"
  desc "CLI for ISO standards lookup via the official ISO Open Data catalogue"
  homepage "https://github.com/Robworks-Code/iso-lookup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iso"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iso"]
    end
  end

  # No zap stanza required

end
